# Website settings
baseurl: ""
url: "https://luna-xue.github.io"
icon: "/assets/img/icons/x.png"

# Internal nav
nav:
  main:
    Publications: "/pages/research"
    "UHM WINGS Lab": "/pages/team"
    Teaching: "/pages/teaching"
    Projects: "/pages/projects"
    "Awards & Activities": "/pages/awards"
    Docs: "/pages/docs"

# Bio settings
name: "Xiaochan Xue"
title: "Xiaochan Xue"
description: "Assistant Professor at University of Hawaiʻi at Mānoa. Research in wireless communication, cybersecurity, and AI-native trustworthy wireless systems."
thumbnail_path: "XXC.png"   # 你需要把头像放到 assets/img/luna.jpg 或改成现有文件名
website_repo_url: "https://github.com/luna-xue"
contact_urls:
  # CV: 
  #   url: "assets/files/CV_Xiaochan.pdf"
  #   label: "CV"
  #   icon: "file-text-o"
  email:
    url: "mailto:xxue@hawaii.edu"
    label: "Email"
    value: "xxue@hawaii.edu"
    icon: "envelope-square"
  scholar:
    url: "https://scholar.google.com/citations?user=rhcjOdQAAAAJ"
    label: "Google Scholar"
    icon: "graduation-cap"
  github:
    url: "https://github.com/luna-xue"
    label: "GitHub"
    icon: "github-square"
  linkedin:
    url: "https://www.linkedin.com/in/xiaochan-xue-2b7b75227/"
    label: "LinkedIn"
    icon: "linkedin-square"
  orcid:
    url: "https://orcid.org/0000-0003-0432-0581"
    label: "ORCID"
    icon: "orcid"
  dblp:
    url: "https://dblp.org/pid/245/3162.html"
    label: "DBLP"
    icon: "book"


# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: compressed
highlighter: rouge
timezone: "Pacific/Honolulu"

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
